permalink: pretty

title:       Florian Preis
description: Life science consulting, side projects, and photography.
url:         https://preis.works
author:      Florian Preis

linkedin:    florianpreis
instagram:   florianprice

theme: null
